DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
CREATE TABLE CUSTOMER
        (CUSTOMERID                NUMBER(8)        NOT NULL,
         CUSTOMERFNAME        VARCHAR(25)        NOT NULL,
         CUSTOMERMINITIAL        CHAR(1),
         CUSTOMERLNAME        VARCHAR(25)        NOT NULL,
         CUSTOMERADDRESS        VARCHAR(30)        NOT NULL,
         CUSTOMERCITY        VARCHAR(20)        NOT NULL,
         CUSTOMERZIP        VARCHAR(9)        NOT NULL,
         CUSTOMERPHONE        VARCHAR(15)        NOT NULL,
         CUSTOMEREMAIL        VARCHAR(30)        NOT NULL,
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMERID));




DROP TABLE STORE CASCADE CONSTRAINTS;
CREATE TABLE STORE
        (STOREID                        NUMBER(3)        NOT NULL,
         STOREADDRESS                VARCHAR(30)        NOT NULL,
         STORECITY                        VARCHAR(20)        NOT NULL,
         STOREZIP                        VARCHAR(9)        NOT NULL,
         STOREPHONE                        VARCHAR(17)        NOT NULL,
         STORESQUAREFOOTAGE        VARCHAR(4)        NOT NULL,
         STOREMANAGERFNAME        VARCHAR(25)        NOT NULL,
         STOREMANAGERLNAME        VARCHAR(25)        NOT NULL,
         STOREMONTHLYRENT        VARCHAR(5)        NOT NULL,
CONSTRAINT STORE_PK PRIMARY KEY (STOREID));




DROP TABLE MENUITEM CASCADE CONSTRAINTS;
CREATE TABLE MENUITEM
        (MENUITEMID                VARCHAR(4)        NOT NULL,
         MENUITEMNAME        VARCHAR(30)        NOT NULL,
         MENUITEMPRICE        VARCHAR(15)        NOT NULL,
         MENUITEMTYPE        VARCHAR(12)        NOT NULL,
CONSTRAINT MENUITEM_PK PRIMARY KEY (MENUITEMID));




DROP TABLE ORDERS CASCADE CONSTRAINTS;
CREATE TABLE ORDERS
        (ORDERID                        VARCHAR(5)        NOT NULL,
         ORDERTOTAL                        VARCHAR(15)        NOT NULL,
         ORDERTYPE                        VARCHAR(8)        NOT NULL
CHECK (ORDERTYPE IN ('DELIVERY', 'PICKUP')),
         ORDERTIME                        VARCHAR(8)                NOT NULL,
         ORDERDATE                        VARCHAR(10)                NOT NULL,
         ORDERPAYMENTTYPE                VARCHAR(12)        NOT NULL
CHECK (ORDERPAYMENTTYPE IN ('CASH', 'CHECK', 'CREDIT CARD', 'DEBIT')),
         CUSTOMERID                        NUMBER(8)        NOT NULL,
         STOREID                        NUMBER(3)        NOT NULL,
CONSTRAINT ORDERS_PK PRIMARY KEY (ORDERID),
CONSTRAINT ORDERS_FK1 FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID),
CONSTRAINT ORDERS_FK2 FOREIGN KEY (STOREID) REFERENCES STORE(STOREID));








DROP TABLE ORDEREDITEMS CASCADE CONSTRAINTS;
CREATE TABLE ORDEREDITEMS
        (ORDEREDITEMSID                VARCHAR(5)        NOT NULL,
         ORDEREDITEMSQTY                NUMBER(38)        NOT NULL,
         ORDERID                        VARCHAR(5)        NOT NULL,
         MENUITEMID                        VARCHAR(4)        NOT NULL,
CONSTRAINT ORDEREDITEMS_PK PRIMARY KEY (ORDEREDITEMSID),
CONSTRAINT ORDEREDITEMS_FK1 FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID),
CONSTRAINT ORDEREDITEMS_FK2 FOREIGN KEY (MENUITEMID) REFERENCES MENUITEM(MENUITEMID));
        




DROP TABLE DELIVERY CASCADE CONSTRAINTS;
CREATE TABLE DELIVERY
        (DELIVERYID                VARCHAR(5)        NOT NULL,
         DELIVERYTIME        VARCHAR(9)                NOT NULL,
         DELIVERYDATE        VARCHAR(10)                NOT NULL,
         ORDERID                VARCHAR(5)        NOT NULL,
CONSTRAINT DELIVERY_PK PRIMARY KEY (DELIVERYID),
CONSTRAINT DELIVERY_FK FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID));








DROP TABLE PICKUP CASCADE CONSTRAINTS;
CREATE TABLE PICKUP
        (PICKUPID                VARCHAR(5)        NOT NULL,
         PICKUPTIME                VARCHAR(8)                NOT NULL,
         PICKUPDATE                VARCHAR(10)                NOT NULL,
         ORDERID                VARCHAR(5)        NOT NULL,
CONSTRAINT PICKUP_PK PRIMARY KEY (PICKUPID),
CONSTRAINT PICKUP_FK FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID));