SELECT * FROM MENUITEM
WHERE MENUITEMPRICE > 10
AND (MENUITEMTYPE='Veggie' OR MENUITEMTYPE='Vegan');


SELECT COUNT(DISTINCT (MENUITEMNAME))
FROM MENUITEM
WHERE MENUITEMTYPE = 'Meat'
AND MENUITEMPRICE < 10;


SELECT STOREID, SUM(ORDERTOTAL)
FROM ORDERS
GROUP BY STOREID;


SELECT MENUITEMNAME, ORDEREDITEMSQTY
FROM MENUITEM
JOIN ORDEREDITEMS
ON MENUITEM.MENUITEMID = ORDEREDITEMS.MENUITEMID;


SELECT *
FROM ORDERS, PICKUP
WHERE ORDERS.ORDERID = PICKUP.ORDERID
AND ORDERPAYMENTTYPE = 'DEBIT'
AND STOREID = '249';


SELECT *
FROM CUSTOMER
WHERE CUSTOMERID IN
(SELECT CUSTOMERID
FROM ORDERS WHERE ORDERPAYMENTTYPE = 'CASH' AND CUSTOMERPHONE LIKE '%510%');


SELECT CUSTOMER.CUSTOMERFNAME, CUSTOMER.CUSTOMERLNAME, ORDERID
FROM CUSTOMER
INNER JOIN ORDERS
ON CUSTOMER.CUSTOMERID = ORDERS.CUSTOMERID
ORDER BY CUSTOMER.CUSTOMERLNAME;


SELECT X.ORDEREDITEMSID, P.MENUITEMID, P.MENUITEMNAME, X.ORDEREDITEMSQTY, P.MENUITEMPRICE, (X.ORDEREDITEMSQTY*P.MENUITEMPRICE) TOTAL
FROM ORDEREDITEMS X, MENUITEM P
WHERE X.MENUITEMID = P.MENUITEMID;


SELECT store.storeID, store.storeCity, storeManagerFName||' '||storeManagerLName AS storeManager, store.storePhone
FROM store;


SELECT orders.orderDate, orders.orderType, orders.orderPaymentType, store.storeCity
FROM orders INNER JOIN store ON orders.storeID = store.storeID
WHERE (((orders.orderDate) = '01-May-13'))
ORDER BY orders.orderDate;


SELECT store.storeID, store.storeCity, Count(orders.orderType) AS CountOforderType
FROM store INNER JOIN orders ON store.storeID = orders.storeID
WHERE (orders.orderType = 'DELIVERY')
GROUP BY store.storeID, store.storeCity;


SELECT store.storeID, store.storeCity, Count(orders.orderType) AS CountOforderType
FROM store INNER JOIN orders ON store.storeID = orders.storeID
WHERE (orders.orderType = 'PICKUP')
GROUP BY store.storeID, store.storeCity;




